# This file was generated by GoReleaser. DO NOT EDIT.
class BusFactor < Formula
  desc "CLI app to calculate Bus/Truck/Pony factory from git history"
  homepage ""
  version "1.0.0"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/elek/bus-factor/releases/download/v1.0.0/bus-factor_1.0.0_Darwin_x86_64.tar.gz"
    sha256 "c850f8461d0c0cf0ec53226566753857b72fadaeae6d125643ca94ca8f64978b"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/elek/bus-factor/releases/download/v1.0.0/bus-factor_1.0.0_Linux_x86_64.tar.gz"
      sha256 "b592b6a1db893fbbb14c28cb4430d5ef88a5084e4147cddb5603de711aeea77f"
    end
  end

  def install
    bin.install "bus-factor"
  end
end
