# This file was generated by GoReleaser. DO NOT EDIT.
class Flekszible < Formula
  desc "Composition based kubernetes resource file manager"
  homepage ""
  version "1.8.0"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/elek/flekszible/releases/download/v1.8.0/flekszible_1.8.0_Darwin_x86_64.tar.gz"
    sha256 "cf592f6a80d7d06cba936a8f821b030f20da5b9e92621c2b57205637700cc3a7"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/elek/flekszible/releases/download/v1.8.0/flekszible_1.8.0_Linux_x86_64.tar.gz"
      sha256 "417821bfa87510c1f6fd529d3fddd04150d88cf4bfd32dc73f61906549e6d6fa"
    end
  end

  def install
    bin.install "flekszible"
  end
end
