# This file was generated by GoReleaser. DO NOT EDIT.
class Flekszible < Formula
  desc "Composition based kubernetes resource file manager"
  homepage ""
  version "2.0.3"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/elek/flekszible/releases/download/v2.0.3/flekszible_2.0.3_Darwin_x86_64.tar.gz"
    sha256 "e1500f2538f4074f370155f7ad92809f6d21c5852307c48638effa4778b640f4"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/elek/flekszible/releases/download/v2.0.3/flekszible_2.0.3_Linux_x86_64.tar.gz"
      sha256 "9050df8347264dd0dfcd70d2ddc3b468178cb186f21885d311b577a99624a9fb"
    end
  end

  def install
    bin.install "flekszible"
  end
end
