# This file was generated by GoReleaser. DO NOT EDIT.
class Ogh < Formula
  desc "Helper script for Apache Hadoop Ozone development"
  homepage ""
  version "1.0.0"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/elek/ogh/releases/download/v1.0.0/ogh_1.0.0_Darwin_x86_64.tar.gz"
    sha256 "40621d314976f8b4556c4a971842e67801177f29df6331f06f950dcad2c4409e"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/elek/ogh/releases/download/v1.0.0/ogh_1.0.0_Linux_x86_64.tar.gz"
      sha256 "e93608a6697301dbaafa9369f9fadf82c7dda0e267e692360513d90f018e2965"
    end
  end

  def install
    bin.install "ogh"
  end
end
